### ISSUE TITLE
Release tarballs

### ISSUE THREAD

**Issue by geofffranks** [orange-cloudfoundry/cassandra-boshrelease#50]
Are the final release tarballs for this boshrelease available anywhere? Not seeing them attached to the releases on GH, or on bosh.io

**Comment by bgandon** [comment]
Oh, that's right. We plan to submit this release to bosh.io eventually.
In the meantime, we should provide compiled tarballs in the “releases” section of this repo.
I'll keep you updated here.

**Comment by bgandon** [comment]
I've uploaded the tarball for [version 6](https://github.com/orange-cloudfoundry/cassandra-boshrelease/releases/tag/v6).
You'll be interested to know that the v7 we are preparing has a lot of breaking changes. They will be documented in the release notes.

**Comment by geofffranks** [comment]
@bgandon Do you know when v7 will be released? There are some fixes we're looking to get that are on master, but not yet in a final release

**Comment by bgandon** [comment]
We cut a v7 too fast last week, and it has many issues. We'll merge a PR to fix those and we plan to cut a stable v8 tomorrow.

**Comment by bgandon** [comment]
And we are done with the [v8](https://github.com/orange-cloudfoundry/cassandra-boshrelease/releases/tag/v8)! Closing this issue.
